#pragma once
#include <xband/connection_lifecycle.hpp>
#include <xband/message_pipeline.hpp>
#include <stdexcept>

namespace xband::protocol {
// Immutable configured identities, one owner thread shared by all connections.
// Plaintext key comparison is a configured-peer check, NOT secure authentication.
class EndpointRegistry {
public:
    struct Identity { std::string name, key; };
    enum class Result { acquired, denied, busy };
    explicit EndpointRegistry(std::vector<Identity> identities) {
        if (identities.empty() || identities.size() > 32) throw std::invalid_argument("Identity count");
        for (auto &identity : identities) {
            if (!endpoint(identity.name) || !keyValid(identity.key)) throw std::invalid_argument("Invalid identity configuration");
            for (const auto &slot : slots_) if (slot.identity.name == identity.name) throw std::invalid_argument("Duplicate identity");
            slots_.push_back({std::move(identity), nullptr});
        }
    }
    EndpointRegistry(const EndpointRegistry &) = delete;
    EndpointRegistry &operator=(const EndpointRegistry &) = delete;
    Result acquire(std::string_view name, std::string_view key, const void *owner) noexcept {
        if (!owner) return Result::denied;
        for (auto &slot : slots_) if (slot.identity.name == name) {
            if (slot.identity.key != key) return Result::denied;
            if (slot.owner) return Result::busy;
            slot.owner = owner; return Result::acquired;
        }
        return Result::denied;
    }
    void release(const void *owner) noexcept {
        for (auto &slot : slots_) if (slot.owner == owner) slot.owner = nullptr;
    }
private:
    static bool keyValid(std::string_view key) noexcept {
        if (key.size() != 64) return false;
        for (const char c : key) if (!((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f'))) return false;
        return true;
    }
    struct Slot { Identity identity; const void *owner; };
    std::vector<Slot> slots_;
};

// Fresh object per accepted TCP connection; lifecycle has already begun.
// Registry/lifecycle outlive this object; this object retains the reservation for
// the ENTIRE connection, including the subsequent ServiceConnection lifetime.
// No callbacks/reentrancy. No secrets logged or included in failure responses.
class ServerHandshake {
public:
    enum class State { waiting, replying, accepted, failed };
    enum class Failure { none, protocol, denied, busy, lifecycle, internal };
    ServerHandshake(ConnectionLifecycle &connection, uint64_t generation, EndpointRegistry &registry)
        : connection_(connection), generation_(generation), registry_(registry) {}
    ServerHandshake(const ServerHandshake &) = delete;
    ServerHandshake &operator=(const ServerHandshake &) = delete;
    ~ServerHandshake() { disconnect(); }
    // Feed only until one hello is complete. Caller retains the remaining TCP
    // bytes; never forward them to the service until accepted. Session token must
    // be freshly generated by the OS host, not supplied by the client.
    MessageInbox::FeedResult feed(std::span<const uint8_t> bytes, uint64_t now, std::string_view fresh_session) noexcept {
        if (!poll(now)) return {0, MessageInbox::Status::failed};
        if (state_ != State::waiting) return {0, MessageInbox::Status::ready};
        try {
            auto result = inbox_.feed(bytes);
            if (result.status == MessageInbox::Status::failed) fail(Failure::protocol);
            else if (result.status == MessageInbox::Status::ready) {
                const auto &m = *inbox_.peek();
                if (m["type"] != "hello" || m["id"] != "1" || !token(fresh_session)) {
                    fail(Failure::protocol);
                } else {
                    name_ = m["endpoint"].get<std::string>();
                    const auto acquired = registry_.acquire(name_, m["body"]["auth_key"].get_ref<const std::string &>(), this);
                    if (acquired != EndpointRegistry::Result::acquired) fail(acquired == EndpointRegistry::Result::busy ? Failure::busy : Failure::denied);
                    else if (!connection_.hello(generation_, name_, now)) fail(Failure::lifecycle);
                    else {
                        session_ = fresh_session; clock_hz_ = m["body"]["clock_hz"].get<uint64_t>();
                        const auto text = nlohmann::json{{"v", 2}, {"type", "hello_ok"}, {"endpoint", name_}, {"session", ""},
                            {"id", "1"}, {"reply_to", "1"}, {"body", {{"new_session", session_}, {"max_chunk", 4096}, {"rx_window", 65536}}}}.dump();
                        if (output_.enqueue(std::span(reinterpret_cast<const uint8_t *>(text.data()), text.size())) != FrameQueue::Result::ok) fail(Failure::internal);
                        else { inbox_.reset(); state_ = State::replying; }
                    }
                }
            }
            if (state_ == State::failed) result.status = MessageInbox::Status::failed;
            return result;
        } catch (...) { fail(Failure::internal); return {0, MessageInbox::Status::failed}; }
    }
    bool poll(uint64_t now) noexcept {
        if (state_ == State::failed) return false;
        const auto expected = state_ == State::waiting ? ConnectionLifecycle::State::hello_wait :
            state_ == State::replying ? ConnectionLifecycle::State::verifying : ConnectionLifecycle::State::active;
        if (connection_.generation() != generation_ || connection_.state() != expected || !connection_.poll(generation_, now)) {
            fail(Failure::lifecycle); return false;
        }
        return true;
    }
    std::span<const uint8_t> output() const noexcept {
        return state_ == State::replying && connection_.generation() == generation_ &&
            connection_.state() == ConnectionLifecycle::State::verifying ? output_.peek() : std::span<const uint8_t>{};
    }
    bool sent(size_t count, uint64_t now) noexcept {
        if (!poll(now)) return false;
        if (state_ != State::replying || !output_.consume(count)) { fail(Failure::protocol); return false; }
        if (!output_.pendingBytes()) {
            if (!connection_.authenticationCompleted(generation_, true, session_, now)) { fail(Failure::lifecycle); return false; }
            state_ = State::accepted;
        }
        return true;
    }
    State state() const noexcept { return state_; }
    Failure failure() const noexcept { return failure_; }
    std::string_view name() const noexcept { return state_ == State::accepted ? name_ : std::string_view{}; }
    std::string_view session() const noexcept { return state_ == State::accepted ? session_ : std::string_view{}; }
    uint64_t clockHz() const noexcept { return state_ == State::accepted ? clock_hz_ : 0; }
    void disconnect() noexcept {
        registry_.release(this); output_.reset(); inbox_.reset(); name_.clear(); session_.clear(); clock_hz_ = 0;
        state_ = State::failed;
        if (connection_.generation() == generation_) connection_.close();
    }
private:
    void fail(Failure reason) noexcept { failure_ = reason; disconnect(); }
    ConnectionLifecycle &connection_; uint64_t generation_; EndpointRegistry &registry_;
    MessageInbox inbox_; FrameQueue output_; std::string name_, session_;
    uint64_t clock_hz_ = 0;
    State state_ = State::waiting; Failure failure_ = Failure::none;
};
}
